lesson 1 homework
js-tasks-ru/jsbasic-20230116-2_a-m-chalkov pull request #2
Opened 2023-01-23 15:53 UTC by amichalkov

1-module tasks 2,3,4,5 completed

2023-01-23 15:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-23 16:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-23 16:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-24 11:17 UTC, SinimaWath requested changes

2023-01-24 11:17 UTC, SinimaWath commented on 1-module/4-task/index.js
> +      if ( str.toLowerCase().indexOf(dict[entry]) != -1 ) {
indexOf - лучше заменить на includes - будет более читаемо и ожидаемо

2023-01-24 11:17 UTC, SinimaWath commented on 1-module/4-task/index.js
> +          retval = true;
Если нашел хоть одно совпадение, то дальше нет смысла выполнять код.

поэтому: `return true`

2023-01-24 11:17 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  dict.push('1xbet', 'xxx');
Если заранее знаешь, какие елементы есть в массиве то:
`const dict = ['1xbet', 'xxx']`

2023-01-24 11:17 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  return newstr;
Тут можно переписать без лишних конструкций:
```
if (str.length > maxlength) {
  return str.slice(0,newlen) + '…'
}

return str;
```

2023-01-24 11:17 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return f;
```
if (n == 0) {
  return 1;
}

n = n - 1;
while (n > 0) {
    f = f * n;
    n = n - 1;
}

return f;

```

Так станет код понятней -> меньше вложенность

2023-01-24 22:05 UTC, amichalkov commented on 1-module/4-task/index.js
> +      if ( str.toLowerCase().indexOf(dict[entry]) != -1 ) {
да, я делал еще до того как досмотрел урок - потом понял, что includes удобнее, но уже закомитил. но спасибо за совет.

2023-01-24 22:06 UTC, amichalkov commented on 1-module/4-task/index.js
> +          retval = true;
логично. привычка из другой области где нужно явным образом завершать все циклы

2023-01-24 22:07 UTC, amichalkov commented on 1-module/4-task/index.js
> +  dict.push('1xbet', 'xxx');
теперь уже понимаю

2023-01-24 22:08 UTC, amichalkov commented on 1-module/5-task/index.js
> +  return newstr;
тут тоже понятно. всё те же привычки что и в 4м таске работают :)

2023-01-24 22:10 UTC, amichalkov commented on 1-module/1-task/index.js
> +  return f;
хорошо что не работать мне на работе с этим языком - привычки писать максимально императивно меня тут не отпускает :)

2023-01-24 22:15 UTC, amichalkov commented
просьба принять pr в оригинальном виде для сохранения не оптимального кода с целью сохранения наглядности

2023-01-26 01:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-26 01:05 UTC, amichalkov commented
added lesson 2 homework

2023-01-26 13:28 UTC, SinimaWath requested changes

2023-01-26 13:28 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    this['y'] = b;
тут нет необходимости в вычисляемых свойствах

2023-01-26 13:28 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  sum = 0;
Это не создание переменной, а запись в глобальный обьект.  Нужен let

2023-01-29 14:45 UTC, SinimaWath approved these changes

2023-01-29 14:46 UTC, merged